
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.PrintWriter;
import java.net.Inet4Address;
import java.net.InetAddress;
import java.net.ServerSocket;
import java.net.Socket;
import java.net.SocketException;
import java.net.SocketTimeoutException;
import java.net.UnknownHostException;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.Timer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Andy Li
 */
public class ChatJFrame extends JFrame implements ActionListener {

    /**
     * Creates new form ChatJFrame
     */
//    private final int PUBLIC_CHAT = 0, PRIVATE_CHAT = 1;
    private ChatInterface node;
    private String myAddress;
    private Timer timer;
    private boolean stopRequested;

    public ChatJFrame() throws UnknownHostException {
        initComponents();
        this.setTitle("PUBLIC CHAT ROOM");
        myAddress = Inet4Address.getLocalHost().getHostAddress();
        myHost.setText(myAddress);
        chatRoomHost.setText("192.168.1.9");
        bSend.setEnabled(false);
        bLeave.setEnabled(false);
        bSend.addActionListener(this);
        bCreate.addActionListener(this);
        bJoin.addActionListener(this);
        bLeave.addActionListener(this);
        timer = new Timer(50, this);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tMessage = new javax.swing.JTextArea();
        bSend = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        myHost = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tPort = new javax.swing.JTextField();
        bCreate = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        chatRoomHost = new javax.swing.JTextField();
        bJoin = new javax.swing.JButton();
        bLeave = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tPublic = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tMessage.setColumns(20);
        tMessage.setRows(5);
        jScrollPane2.setViewportView(tMessage);

        bSend.setText("Send");

        jPanel1.setLayout(new java.awt.GridLayout(6, 1));

        jLabel1.setText("Your Address: ");
        jPanel2.add(jLabel1);

        myHost.setText("255.255.255.255");
        jPanel2.add(myHost);

        jPanel1.add(jPanel2);

        jLabel3.setText("Room Number:");
        jPanel3.add(jLabel3);

        tPort.setText("1099");
        jPanel3.add(tPort);

        jPanel1.add(jPanel3);

        bCreate.setText("Create");
        jPanel1.add(bCreate);

        jLabel2.setText("OR");
        jPanel1.add(jLabel2);

        jLabel4.setText("Room Address: ");
        jPanel4.add(jLabel4);

        chatRoomHost.setText("255.255.255.255");
        jPanel4.add(chatRoomHost);

        jPanel1.add(jPanel4);

        bJoin.setText("Join");
        jPanel1.add(bJoin);

        bLeave.setText("Leave");

        tPublic.setColumns(20);
        tPublic.setRows(5);
        jScrollPane1.setViewportView(tPublic);

        jTabbedPane1.addTab("Public Chat", jScrollPane1);

        jLabel5.setText("Say something");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bSend)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bLeave))))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bSend)
                            .addComponent(bLeave)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChatJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChatJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChatJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChatJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ChatJFrame().setVisible(true);
                } catch (UnknownHostException ex) {
                    Logger.getLogger(ChatJFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCreate;
    private javax.swing.JButton bJoin;
    private javax.swing.JButton bLeave;
    private javax.swing.JButton bSend;
    private javax.swing.JTextField chatRoomHost;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel myHost;
    private javax.swing.JTextArea tMessage;
    private javax.swing.JTextField tPort;
    private javax.swing.JTextArea tPublic;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        if (e.getSource() == bCreate) {
            try {
                int port = Integer.parseInt(tPort.getText());
                node = new ChatRoom(port);
                node.UpdateTimestamp(myAddress);
                bSend.setEnabled(true);
                bCreate.setEnabled(false);
                bJoin.setEnabled(false);
                chatRoomHost.setEditable(false);
                bLeave.setEnabled(true);

                timer.start();

            } catch (NumberFormatException ex) {
                System.out.println("invalid port number");
            } catch (RemoteException ex) {
                Logger.getLogger(ChatJFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else if (e.getSource() == bJoin) {
            Registry registry;
            try {
                registry = LocateRegistry.getRegistry(chatRoomHost.getText());
//                registry = LocateRegistry.getRegistry("192.168.1.2");
                node = (ChatInterface) registry.lookup("chat");
                node.UpdateTimestamp(myAddress);
                bSend.setEnabled(true);
                bCreate.setEnabled(false);
                bJoin.setEnabled(false);
                bLeave.setEnabled(true);
                chatRoomHost.setEditable(false);
                timer.start();

            } catch (RemoteException ex) {
                Logger.getLogger(ChatJFrame.class.getName()).log(Level.SEVERE, null, ex);
            } catch (NotBoundException ex) {
                Logger.getLogger(ChatJFrame.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else if (e.getSource() == bLeave) {
            node = null;
            bSend.setEnabled(false);
            bCreate.setEnabled(true);
            bJoin.setEnabled(true);
            chatRoomHost.setEditable(true);

            timer.stop();
        } else if (e.getSource() == bSend) {
            try {
                if (tMessage.getText().length() > 0) {
                    node.createChat(myAddress + ": \n\t" + tMessage.getText());
                    tMessage.setText("");
                    updateChatBoard();
                }

            } catch (RemoteException ex) {
                Logger.getLogger(ChatJFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else if (e.getSource() == timer) {
            try {
                updateChatBoard();
            } catch (RemoteException ex) {
                Logger.getLogger(ChatJFrame.class.getName()).log(Level.SEVERE, null, ex);
            }

        } 
    }

    private void updateChatBoard() throws RemoteException {
        if (node != null) {
            ArrayList<String> chatHistory = node.getChatHistory();
            final StringBuilder stringBuilder = new StringBuilder();
//            for (int i = 0; i < chatHistory.size() && i < 15;
//                    i++) {
//                stringBuilder.append(chatHistory.get(i));
//                stringBuilder.append("\n");
//            }
            for (String m : chatHistory) {
                stringBuilder.append(m);
                stringBuilder.append("\n");
            }
            tPublic.setText(stringBuilder.toString());
        }
    }
////////////////////////////////////////////////////////////////////

}
